version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_DB=easyTabledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5431:5432'
volumes:
  postgres_db:
    driver: local
